name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  update_db_version:
    name: Update DB Version
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/db-version.yml

  linters:
    name: Run linters
    needs: update_db_version
    if: ${{ always() }}
    uses: ./.github/workflows/linters.yml

  rust_check:
    name: Run check
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/rust-check.yml

  linters_cargo:
    name: Run Cargo linters
    needs: rust_check
    uses: ./.github/workflows/linters-cargo.yml

  coverage:
    name: Run Coverage
    needs: update_db_version
    if: ${{ always() }}
    secrets: inherit
    uses: ./.github/workflows/coverage.yml

  build:
    name: Build Madara
    needs: update_db_version
    if: ${{ always() }}
    uses: ./.github/workflows/build.yml

  js_test:
    name: Run JS Tests
    needs: build
    if: ${{ always() }}
    uses: ./.github/workflows/starknet-js-test.yml
