---
name: Task - Run Cargo tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Launch Anvil
        run: anvil --fork-url $ANVIL_FORK_URL --fork-block-number $ANVIL_BLOCK_NUMBER &
        env:
          ANVIL_FORK_URL: "https://eth.merkle.io"
          ANVIL_BLOCK_NUMBER: 20395662
      - name: Wait for Anvil to be ready
        run: |
          while ! nc -z localhost 8545; do
            sleep 1
          done
      # TODO : For now madara binary is stored in aws s3 bucket :
      #        After the proper release binaries are implemented
      #        We can directly use that and we can remove this
      #        temporary AWS implementation
      - name: Download madara binary for l2 client testing
        run: |
          curl -L https://madara-test-binary.s3.us-west-1.amazonaws.com/madara-linux -o ./test-artifacts/madara
          chmod +x ./test-artifacts/madara

      - name: Run unit tests
        run: |
          cargo test --workspace
        env:
          PROPTEST_CASES: 2
